### ISSUE TITLE
Error in `Terms` when no intercept is requested

### ISSUE THREAD

**Issue by andreasnoack** [JuliaStats/DataFrames.jl#574]
This does not work
```
df = DataFrame(A = 1:4, B = ["M", "F", "F", "M"]);
ModelMatrix(ModelFrame(A~B-1, df))
ERROR: no method convert(Type{Expr}, Array{Any,1})
 in unshift! at array.jl:511
 in Terms at /Users/andreasnoackjensen/.julia/v0.3/DataFrames/src/formula/formula.jl:145
 in ModelFrame at /Users/andreasnoackjensen/.julia/v0.3/DataFrames/src/formula/formula.jl:174
```
but this does
```
julia> ModelMatrix(ModelFrame(A~B+(-1), df))
ModelMatrix{Float64}(4x1 Array{Float64,2}:
 1.0
 0.0
 0.0
 1.0,[1])
```

**Comment by ararslan** [comment]
This has been fixed now, hasn't it?

**Comment by nalimilan** [comment]
Still doesn't work AFAICT (even after converting `B` to a `CategoricalArray`).

**Comment by kleinschmidt** [comment]
It's the `-1` that's the issue I think. `+0` should work (and have the same effect).

**Comment by nalimilan** [comment]
But do we still want to support `-1`?

**Comment by ararslan** [comment]
It might make more sense to have a single, consistent means of requesting no intercept, and IMO `+0` is nicer than `-1`.

**Comment by kleinschmidt** [comment]
I agree. And, in fact, we might go so far as to make no intercept the default, so you'd need to explicitly have `+1` to add an intercept.

**Comment by ararslan** [comment]
On the one hand, I like that because it requires being explicit (which is almost always a good thing) and will require people to think harder about the exact model they're fitting, but on the other hand I think it could be surprising for some people since implicit intercept is the default in R, SAS, and likely others as well. So... I'm undecided on that.

**Comment by nalimilan** [comment]
We've had that discuss in many different places already, but I'll restate my preferred solution: require people to either say `1 + ` or `0 + `, else raise an error with an explanation. That's the only way to get rid of the implicit intercept without trapping people into fitting weird models.

**Comment by ararslan** [comment]
+1 to Milan's proposal. And if we end up not doing that, +1 to Doug's.

**Comment by johnmyleswhite** [comment]
Explicitness is good by me, so I like Milan's solution.
